# Generated by Django 3.2.20 on 2023-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='packetQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default='No detailed Instructions', max_length=5000),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipeQuantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
