# Generated by Django 3.2.20 on 2023-08-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230803_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='packetQuantity',
            new_name='packetQuantityGrams',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='recipeQuantity',
            new_name='recipeQuantityGrams',
        ),
    ]
